### ISSUE TITLE
Failed convertion from boolean false to NULL pointer in Aria library.

### ISSUE THREAD

**Issue by luis109** [rgmaidana/P3AT-dune-driver#1]
Can't convert (boolean)false->(int)0->(*)NULL when returning.
This happens here:
https://github.com/rgmaidana/P3AT-dune-driver/blob/master/vendor/libraries/aria/src/ArCameraCollection.cpp#L568-L570

https://github.com/rgmaidana/P3AT-dune-driver/blob/master/vendor/libraries/aria/src/ArCameraCollection.cpp#L589-L592

https://github.com/rgmaidana/P3AT-dune-driver/blob/master/vendor/libraries/aria/src/ArDataLogger.cpp#L58

https://github.com/rgmaidana/P3AT-dune-driver/blob/master/vendor/libraries/aria/src/ArGPSConnector.cpp#L203

An easy fix would be to simply return NULL.

**Comment by rgmaidana** [comment]
Hello, thanks for opening this issue. It seems this particular error occurs when the compiler tries to convert boolean to NULL, but there is ambiguity due to two or more possible conversions from "false"->0->NULL. As you suggested, returning NULL fixes the issue.
